name: publish to npmjs

on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: 'https://registry.npmjs.org'

      - name: Build the package
        run: yarn pack

      - name: Publish the package
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
